name: CI
on:
  pull_request:
jobs:
  ciJvms:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        java: [ '11', '17', '21' ]
    steps:
      - uses: actions/checkout@v4.1.5
        with:
          fetch-depth: 100
      - name: Fetch tags
        run: git fetch --depth=100 origin +refs/tags/*:refs/tags/*
      - uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'sbt'
      - name: Coursier cache
        uses: coursier/cache-action@v6.4.6
      - name: sbt ci ${{ github.ref }}
        run: ./sbt ci

  ci:
    if: always()
    runs-on: ubuntu-22.04
    needs: [ ciJvms ]
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
